---
- name: A playbook showing the file module
  hosts: planetexpress

  tasks:
   - name: Create directory where Space Station documents will reside
     become_user: root
     become: true
     file:
        # the var "ansible_user" is a host variable AND connection variable
        path: "/home/{{ ansible_user }}/station_docs/"
        state: absent
     
